# Generated by Django 4.2.13 on 2026-03-12 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_supplier_purchase_minqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place_of_manufacture',
            field=models.CharField(blank=True, help_text='Country or place of origin', max_length=200),
        ),
        migrations.CreateModel(
            name='StockCountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjustments', models.JSONField(default=list, help_text='List of {batch_id, old_qty, new_qty}')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_logs', to='core.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
