# Generated by Django 4.2.13 on 2026-03-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventory_audit_product_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches where this product is available', related_name='products', to='core.branch'),
        ),
    ]
