# Generated by Django 4.2.13 on 2026-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_product_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pills_per_strip',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_box',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_strip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('default', 'Default'), ('pills', 'Pills')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='strips_per_box',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
