# Generated by Django 4.2.13 on 2026-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_branches_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('tablets', 'Tablets'), ('capsules', 'Capsules'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment / Cream'), ('spray', 'Spray'), ('drops', 'Drops'), ('suppository', 'Suppository')], default='', max_length=30),
        ),
    ]
